on: [push]

name: Echidna Analysis

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Solidity Compiler
        run: pip3 install solc-select && solc-select install 0.8.9 && solc-select use 0.8.9

      - name: Install Slither Analyzer
        run: pip3 install slither-analyzer

      - name: Install Crytic Compile
        run: pip3 install crytic-compile

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Echidna
        # Use build with fix for reported issue until new version published 
        run: wget -q -c https://nightly.link/crytic/echidna/actions/artifacts/224513612.zip && unzip -q 224513612.zip && tar xzf echidna-test.tar.gz && rm 224513612.zip  && rm echidna-test.tar.gz

      # Property tests
      - name: Fuzz owners
        run: ./echidna-test . --contract OwnerTests --config ./src/echidna/config.yml --test-limit 100000 --format text

      - name: Fuzz mint
        run: ./echidna-test . --contract MintTests --config ./src/echidna/config.yml --test-limit 100000 --format text