on: [push]

name: Slither Analysis

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Slither Analyzer
        run: pip3 install slither-analyzer

      - name: Start Analysis
        run: slither src/MetaFashion.sol --solc-remaps '@openzeppelin/=lib/openzeppelin-contracts/ ERC721A/=lib/ERC721A/contracts/' --filter-paths lib

      # https://github.com/crytic/slither-action/issues/3
      # - uses: crytic/slither-action@v0.1.1
      #   with:
      #     target: 'src/MetaFashion.sol'
      #     slither-args:  '--solc-remaps "@openzeppelin/=lib/openzeppelin-contracts/ ERC721A/=lib/ERC721A/contracts/" --filter-paths lib/'