on: [push]

name: solhint

jobs:
  check:
    name: Solhint security and style guide validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - uses: bahmutov/npm-install@v1
        with:
          install-command: npm install solhint -g

      - name: Run solhint
        run: solhint 'src/**/*.sol'
